### PR TITLE
Set propert version format

### PR DESCRIPTION
**Pull request by pfaion**
1.0.0 instead of 1

### CODE REVIEW

**Comment by papr** [comment]
Why is this necessary? Does PyPI enforce this?

**Comment by pfaion** [comment]
No it does not enforce this, although I read that the recommended versioning scheme is x.y[.z].

Also in the past single digit versions were invalid in python (PEP386), although they are considered valid now (PEP440).

Do we want to stick to **1** as version, and thus stick to a serial versioning scheme? As in **1** -> **2** -> **3** ... ?

**Comment by papr** [comment]
A non-serial serial number is helpful if you need to maintain multiple versions at once. Since we will only maintain the most recent version, we might as well stick with a serial version scheme.

**Comment by pfaion** [comment]
Sounds good.

**Pull request closed without merging**
